mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant_menu.urls'))
]

restaurant_menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MenuListView.as_view(), name='home'),
    path('item/<int:pk>/', views.MenuItemDetailView.as_view(), name='menu_item'),
    path('about/', views.AboutView.as_view(), name='about'),
]

restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
MEAL_TYPE = (
    ('starters', 'Starters'),
    ('salads', 'Salads'),
    ('main_dishes', 'Main dishes'),
    ('desserts', 'Desserts')
)
MEAL_STATUS = (
    (0, 'Unavailable'),
    (1, 'Available')
)


class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True)
    description = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    meal_type = models.CharField(max_length=1000, choices=MEAL_TYPE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    status = models.IntegerField(choices=MEAL_STATUS)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.meal

restaurant_menu/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item, MEAL_TYPE


# Create your views here.
class MenuListView(generic.ListView):
    queryset = Item.objects.order_by('date_created')
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["meals"] = MEAL_TYPE
        return context


class MenuItemDetailView(generic.DetailView):
    model = Item
    template_name = "menu_item_detail.html"


class AboutView(generic.TemplateView):
    template_name = 'about_us.html'

restaurant_menu/templates/about_us.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>About us!</h1>
    <p>Made by Mario Umaña 👨🏻‍💻</p>
    <p>contact me at: marioua289@gmail.com</p>

</div>


{% endblock content %}

restaurant_menu/templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h1>Restaurant Menu!</h1>
    <ul class="list-group list-group-flush">
        {% for meal in meals %}
            <h2 class="pt-5">{{ meal.1 }}</h2>
            {% for row in item_list %}
                {% if row.meal_type == meal.0 %}
                    {% if row.status == 0 %}
                    <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                        <a href="{% url 'menu_item' row.pk %}"><del>{{ row.meal }}</del></a>
                        <span class="badge bg-primary rounded-pill">{{ row.price }}</span>
                    </li>
                    <li class="list-group-item pt-0">
                        <p>{{ row.description }}</p>
                    </li>
                    {% else %}
                    <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                        <a href="{% url 'menu_item' row.pk %}">{{ row.meal }}</a>
                        <span class="badge bg-primary rounded-pill">{{ row.price }}</span>

                    </li>
                     <li class="list-group-item pt-0">
                         <p>{{ row.description }}</p>

                    </li>
                    {% endif %}

                {% endif %}
            {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endblock content %}

restaurant_menu/templates/menu_item_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1 class="pt-5">{{ item.meal }}</h1>
        <p>{{ item.description }}</p>
        <p>$ {{ item.price }}</p>
    </div>
{% endblock content %}